name: Playwright CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run Tests and Generate Report
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Generate Allure report
        if: always() && hashFiles('allure-results/**') != ''
        run: npm run allure:generate

      - name: Upload Allure results artifact
        if: always() && hashFiles('allure-results/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Deploy Allure report to gh-pages
        if: always() && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          destination_dir: allure-reports
          keep_files: true